USE [master]
GO

CREATE DATABASE [AmDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AmDemo', FILENAME = N'C:\Denos\MSSQL\DATA\AmDemo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AmDemo_log', FILENAME = N'C:\Demos\MSSQL\DATA\AmDemo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [AmDemo] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AmDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AmDemo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AmDemo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AmDemo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AmDemo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AmDemo] SET ARITHABORT OFF 
GO

ALTER DATABASE [AmDemo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AmDemo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AmDemo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AmDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AmDemo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AmDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AmDemo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AmDemo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AmDemo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AmDemo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AmDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AmDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AmDemo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AmDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AmDemo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AmDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AmDemo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AmDemo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AmDemo] SET  MULTI_USER 
GO

ALTER DATABASE [AmDemo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AmDemo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AmDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AmDemo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AmDemo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AmDemo] SET QUERY_STORE = OFF
GO

USE [AmDemo]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [AmDemo] SET  READ_WRITE 
GO


/* Populate the database with some test data */
USE [AmDemo]
GO

INSERT INTO dbo.Customers VALUES ('Joe','Bloggs',21,'M',1);
INSERT INTO dbo.Customers VALUES ('Jane','Doe',37,'F',1);
GO